remote_theme: pmarsceill/just-the-docs
color_scheme: "dark"

permalink: pretty
exclude: ["node_modules/", "*.gemspec", "*.gem", "Gemfile", "Gemfile.lock", "package.json", "script/", "LICENSE.txt", "lib/", "bin/", "README.md", "Rakefile"]

# Enable or disable the site search
search_enabled: true

# Aux links for the upper right navigation
aux_links:
  "Just the Docs on GitHub":
    - "//github.com/pmarsceill/just-the-docs"

# Color scheme currently only supports "dark" or nil (default)
color_scheme: nil

---
layout: default
title: Customization
nav_order: 2
---
